/*
 * Jenkinsfile for Rest Assured API Tests
 * 
 * This pipeline:
 * 1. Pulls your repo from GitHub
 * 2. Runs "mvn test" on the Jenkins server
 * 3. Publishes TestNG/Surefire reports
 * 4. Archives the test results
 * 
 * Requirements on Jenkins server:
 * - Java 17+ (JDK)
 * - Maven 3.6+
 * - Pipeline plugin enabled
 */

pipeline {
    agent any

    // Configure Java and Maven tools
    tools {
        jdk 'JDK17'          // Must match the name configured in Jenkins > Manage Jenkins > Tools
        maven 'Maven3'       // Must match the name configured in Jenkins > Manage Jenkins > Tools
    }

    // Optional: Build triggers
    triggers {
        // Trigger on push to main branch
        githubPush()
        
        // OR schedule daily at 2 AM
        // cron('0 2 * * *')
    }

    // Optional: Build parameters
    parameters {
        string(name: 'TEST_ENV', defaultValue: 'staging', description: 'Test environment (dev/staging/prod)')
        booleanParam(name: 'SEND_EMAIL_REPORT', defaultValue: true, description: 'Send email report?')
    }

    environment {
        // Set environment variables for tests
        TEST_ENVIRONMENT = "${params.TEST_ENV}"
        BASE_URL = credentials('api-base-url')  // Store sensitive URLs in Jenkins Credentials
        MAVEN_OPTS = '-Xmx1024m -XX:MaxPermSize=512m'
    }

    stages {
        stage('Checkout') {
            steps {
                echo '========== Stage: Checkout =========='
                git branch: 'main', 
                    url: 'https://github.com/your-username/rest-assured-tests.git'
                echo 'Repository cloned successfully'
            }
        }

        stage('Build') {
            steps {
                echo '========== Stage: Build =========='
                sh 'mvn clean compile'
                echo 'Build successful'
            }
        }

        stage('Run API Tests') {
            steps {
                echo '========== Stage: Run API Tests =========='
                sh 'mvn test'
                echo 'Tests completed'
            }
        }

        stage('Generate Reports') {
            steps {
                echo '========== Stage: Generate Reports =========='
                // TestNG reports are auto-generated by Maven Surefire
                // Additional report generation can go here
                sh 'echo "Test reports available in target/surefire-reports/"'
            }
        }

        stage('Publish Results') {
            steps {
                echo '========== Stage: Publish Results =========='
                // Publish TestNG results to Jenkins
                testng(
                    failOnFailedConfiguration: true,
                    failOnSkippedTests: false,
                    reportFilesPattern: '**/target/surefire-reports/testng-results.xml',
                    skipFailedInvocations: true,
                    verbose: true
                )
                
                // Archive test artifacts
                archiveArtifacts artifacts: '**/target/surefire-reports/**', 
                                 allowEmptyArchive: true
            }
        }
    }

    post {
        always {
            echo '========== Pipeline Completed =========='
            // Clean up workspace (optional)
            cleanWs()
        }

        success {
            echo '✓ All tests PASSED'
            // Send success notification
            script {
                if (params.SEND_EMAIL_REPORT) {
                    emailext(
                        subject: "✓ API Tests PASSED - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                        body: """
                            API Tests Passed Successfully!
                            
                            Job: ${env.JOB_NAME}
                            Build: ${env.BUILD_NUMBER}
                            Duration: ${currentBuild.durationString}
                            
                            View Results: ${env.BUILD_URL}testReport
                        """,
                        to: 'team@company.com',
                        mimeType: 'text/html'
                    )
                }
            }
        }

        failure {
            echo '✗ Tests FAILED'
            // Send failure notification
            script {
                if (params.SEND_EMAIL_REPORT) {
                    emailext(
                        subject: "✗ API Tests FAILED - ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                        body: """
                            API Tests Failed!
                            
                            Job: ${env.JOB_NAME}
                            Build: ${env.BUILD_NUMBER}
                            Duration: ${currentBuild.durationString}
                            
                            View Logs: ${env.BUILD_URL}console
                            View Results: ${env.BUILD_URL}testReport
                        """,
                        to: 'team@company.com',
                        mimeType: 'text/html'
                    )
                }
            }
        }

        unstable {
            echo '⚠ Build is unstable (some tests may have been skipped)'
        }
    }
}

/*
 * HOW TO USE THIS JENKINSFILE
 * ==============================
 * 
 * 1. In Jenkins, create a new "Pipeline" job
 * 2. Under "Pipeline" section, choose "Pipeline script from SCM"
 * 3. Select Git as the SCM
 * 4. Enter your repo URL: https://github.com/your-username/rest-assured-tests.git
 * 5. Set Script Path to: Jenkinsfile
 * 6. Save and run
 * 
 * 
 * REQUIRED JENKINS CONFIGURATION
 * ===============================
 * 
 * Manage Jenkins > Tools:
 *   - JDK Installations
 *       Name: JDK17
 *       JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64 (or your path)
 *   - Maven Installations
 *       Name: Maven3
 *       MAVEN_HOME: /opt/maven (or your path)
 * 
 * Manage Jenkins > Credentials:
 *   - Add Secret text "api-base-url" = "https://api.example.com"
 * 
 * 
 * WHAT JENKINS PROVIDES
 * ======================
 * 
 * ✓ Automated test execution on code push (webhook)
 * ✓ JDK 17 runtime
 * ✓ Maven - downloads all dependencies (Rest Assured, TestNG, etc.)
 * ✓ Test report collection
 * ✓ Email notifications on pass/fail
 * ✓ Build history and trends
 * ✓ Scheduled runs (e.g., daily at 2 AM)
 * ✓ Parameter input (e.g., select test environment)
 * 
 * 
 * YOU STILL PROVIDE
 * ==================
 * 
 * ✗ The .java test files (in GitHub)
 * ✗ The pom.xml (in GitHub)
 * ✗ The Jenkinsfile (in GitHub)
 * 
 * (Jenkins doesn't write code — it runs code)
 */
